.\" Manpage for simple shell Project
.TH man 1 "18 May 2022" "1.0" "simple_shell Project Man Page"


.SH NAME
.simple_shell
\
simple_shell - simple_shell (hsh) is a simple and basic shell, command-lne interpreter that provides you an interface to the Linux system, permit you execute commands like shell (sh) console command.

Take input when you type a command and execute some functions based on that input and show you the execution of that function in other words: the output command.


.SH SYNOPSIS
./hsh
/bin/[command] [option]


.SH DESCRIPTION
Is a simple hsh command language interpreter that executes commands using the path of this command that stored in the bin directory, the shell read from the standard input through the getline command, is based on the shell designed by Ken Thompson

.SH OVERVIEW
Reading from either the terminal or files, simple_shell interprets and executes commands.


.SH BUILTINS

The following builtin commands are supported:

.IT
.B env
- prints the environment variables

.B exit
- exits the program

.B setenv VARIABLE VALUE
- sets the environment

.B unsetenv VARIABLE
- removes elements from the environment


.SH EXAMPLE
$ /bin/ls -l
drwxrwxr-x 1 vagrant vagrant 279 May 17 03:14 README.md
drwxrwxr-x 2 vagrant vagrant 165 May 17 23:46 arguments.c

$ /bin/pwd
/home/vagrant/ALX_shell

$ hhhhh
Does not execute, write valid command: No such file or directory


.SH SEE ALSO
env(1), strtok(3), getline(3), exit(0)


.SH BUGS
If there is a bug, report to https://github.com/Theocode12 or https://github.com/azconcept-droid

.SH AUTHOR
Mutabonwa Sharon and Eric Niyikomeye - Students at ALX.
